name: editor_sdk
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/gmvbr/editor_sdk

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  code_builder: ^4.1.0
